# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs: 
  - job: build_containers
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: docker-compose build express-api
      displayName: 'docker build'
    - script: | 
        mkdir "publish" && \
        docker save cicddemoapp_express-api:latest > ./publish/cicddemoapp_express-ap:latesti.tar 
      displayName: 'save docker image'
    - task: PublishPipelineArtifact@0
      inputs: 
        artifactName: images
        targetPath: './publish'
  - job: integration_tests
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn: 
      - build_containers
    steps:
      - task: DownloadPipelineArtifact@0
        inputs: 
          targetPath: .
          artifactName: images
      - script: docker load < cicddemoapp_express-api:latest.tar
        displayName: 'Loading Express Api'
      - script: docker-compose up -d  express-api postgres-database
        displayName: 'Start Backend'
      - script: |
          cd vue-client
          npm ci
          npx cypress verify
        displayName: 'Setup Cypress'
      - script: npx cypress run --config video=false
        displayName: 'Run Cypress test'

