version: '3'
services:
  pg-docker:
    container_name: pg-docker
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
      - ./postgres-seed:/docker-entrypoint-initdb.d #run these scripts on first container creation
    environment: 
      - POSTGRES_PASSWORD=docker
  pgweb:
    container_name: pgweb  # optional
    restart: always  # optional
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - pg-docker:db  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/postgres?sslmode=disable
    depends_on:
      - pg-docker # my database container is called postgres, not db
